// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Seminar5.Models;

#nullable disable

namespace Seminar5.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20240310164906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Seminar5.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConsumerId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<bool>("isRecieved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Seminar5.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Seminar5.Models.Message", b =>
                {
                    b.HasOne("Seminar5.Models.User", "Author")
                        .WithMany("SendedMessage")
                        .HasForeignKey("AutorId")
                        .HasConstraintName("mesages_from_user_id_fk_author_id");

                    b.HasOne("Seminar5.Models.User", "Consumer")
                        .WithMany("RecievedMessage")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("Seminar5.Models.User", b =>
                {
                    b.Navigation("RecievedMessage");

                    b.Navigation("SendedMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
